name: Update mirror
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror commits
        run: |
          git clone git://vps1.g8bpq.net/linbpq
          cd linbpq
          git remote add mirror https://m0lte:${{secrets.pat}}@github.com/M0LTE/linbpq.git
          #git config user.name "github-actions"
          #git config user.email "github-actions@github.com"
          git pull mirror master --ff-only
          git push mirror
